jobs:
- name: test
  plan:
  - get: jira-resource
    trigger: true
  - task: run-tests
    config:
      platform: linux
      image_resource:
        source:
          repository: danrspencer/jira-resource
        type: docker-image
      inputs:
      - name: jira-resource
      run:
        path: jira-resource/ci/scripts/run-tests

- name: build
  plan:
  - get: jira-resource
    trigger: true
    passed: [ test ]
  - put: version
    params:
      bump: patch
  - put: docker-image-jira-resource
    params:
      build: jira-resource
      tag: version/version
      tag_as_latest: true

- name: major
  plan:
  - put: version
    params:
      bump: major

- name: minor
  plan:
  - put: version
    params:
      bump: minor

resources:
  - name: jira-resource
    type: git
    source:
      uri: git@github.com:danrspencer/jira-resource.git
      branch: master
      private_key: {{private-repo-key}}
      ignore_paths: [ package.json ]

  - name: version
    type: semver
    source:
      driver: git
      uri: git@github.com:danrspencer/jira-resource.git
      branch: version
      private_key: {{private-repo-key}}
      file: version

  - name: docker-image-jira-resource
    type: docker-image
    source:
      repository: danrspencer/jira-resource
      username: danrspencer
      password: boccie.tapestry.conjoint.communal.binary
      email: danrspen@gmail.com
